### ISSUE TITLE
The matched file list appear ONLY after pressing down the backspace key

### ISSUE THREAD

**Issue by na0x2c6** [mattn/ctrlp-matchfuzzy#2]
Thank you for the awesome plugin.

In my environment, the matched file list is empty at the first typing, though once I press down the backspace (or ctrl + h), that come appeared.

![ctrlp-with-matchfuzzy](https://user-images.githubusercontent.com/15692034/93705980-0f925500-fb5d-11ea-9ff4-23ec21e3f12f.gif)

But of course, I want to be able to see the matched file list at the first typing time.

My code:
```vim
if !empty(globpath(&rtp, 'autoload/ctrlp_matchfuzzy.vim'))
    let g:ctrlp_match_func = {'match': 'ctrlp_matchfuzzy#matcher'}
endif
```

I use Vim v8.2.1712 on macOS.
Thanks.

**Comment by mattn** [comment]
Can I see all the configuration variables for CtrlP?

**Comment by mattn** [comment]
Ah, sorry. Could you please try last commit ?

**Comment by na0x2c6** [comment]
At [the last commit](https://github.com/mattn/ctrlp-matchfuzzy/commit/07781dc11bd1b5fabcc8b43269a49f85b960d1e0), I can see the matched files from the beginning of typing!!
Thank you!
