### ISSUE TITLE
Question: what is the easiest way to activate regex mode?

### ISSUE THREAD

**Issue by ompugao** [mattn/ctrlp-matchfuzzy#3]
Currently ctrlp_matchfuzzy ignores all the arguments provided, but I would like to swtich the matcher to regex mode.
How could I use the original regex matcher?

// s:MatchIt function in ctrlp.vim is not public, therefore I think it needs some hack to use it in ctrlp_matchfuzzy#matcher.

**Comment by mattn** [comment]
Please type <kbd>CTRL</kbd>-<kbd>r</kbd>

**Comment by ompugao** [comment]
but matcher is still fuzzy matcher on my side.

**Comment by ompugao** [comment]
![image](https://user-images.githubusercontent.com/954543/101850261-c8849080-3b9c-11eb-8185-c2d12f3d6f58.png)

**Comment by mattn** [comment]
Ah, you're right. Will fix.

**Comment by ompugao** [comment]
:pray: :pray: :pray:

**Comment by mattn** [comment]
Please try last change.

**Comment by ompugao** [comment]
now it is fixed! thank you!
