### ISSUE TITLE
No such hightlight group name: CtrlPLinePre

### ISSUE THREAD

**Issue by ompugao** [mattn/ctrlp-matchfuzzy#4]
The error in title is caused by the lambda function of the timer for redraw, while typing query characters.
I have no idea how this happens and how I can solve it.

OS: ubuntu 20.04
vim version:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 11:55:03)
Included patches: 1-4779
ctrlp.vim: 3ce448c9687ae96dea0caf4da388ecd8d9072f72 // current latest
ctrlp-matchfuzzy.vim: f3c97f48900992f212c5528aeba71b012aeff66d //current latest

![image](https://user-images.githubusercontent.com/954543/163752448-1f261e1e-64b5-47a2-b72d-9859b0c0cf20.png)

Thank you in advance

**Comment by mattn** [comment]
Could you please check [last change](https://github.com/mattn/ctrlp-matchfuzzy/commit/dbf86ae94c2b07eaaaf7cdacc26e0f41240f97a4)?

**Comment by ompugao** [comment]
Now it's fixed. Thank you.
